### PR TITLE
[core] Add elideBlocks to Instantiate cache key

### LINKED ISSUE #5138: Include `elideBlocks` state in `Instantiate` hash
Currently, if you use `elideBlocks` on `Instantiate`, this will have no effect if there is a cache hit. Instead, whether or not you are in an `elideBlocks` scope should factor into the hash so that the following circuit will compile.

In the example below, this will error in `firtool` compilation because of bind-under-bind checking:

``` scala
//> using repository https://central.sonatype.com/repository/maven-snapshots
//> using scala 2.13.18
//> using dep org.chipsalliance::chisel:7.6.0
//> using plugin org.chipsalliance:::chisel-plugin:7.6.0
//> using options -unchecked -deprecation -language:reflectiveCalls -feature -Xcheckinit
//> using options -Xfatal-warnings -Ywarn-dead-code -Ywarn-unused -Ymacro-annotations

import chisel3._
import chisel3.experimental.hierarchy.{instantiable, public, Instantiate}
import circt.stage.ChiselStage

@instantiable
class Bar extends Module {
  @public
  val in = dontTouch(IO(Input(Bool())))
  layer.block(layers.Verification.Assert) {
    val x = dontTouch(Wire(Bool()))
    x :<= DontCare
  }
}

class Foo extends Module {
  val bar = Instantiate(new Bar)
  layer.block(layers.Verification) {
    val bar = layer.elideBlocks {
      Instantiate(new Bar)
    }
    bar.in :<= dontTouch(WireInit(true.B))
  }
}

object Main extends App {
  println(
    ChiselStage.emitSystemVerilog(
      gen = new Foo,
      firtoolOpts = Array(
        "-disable-layers=Verification.Assume,Verification.Cover",
        "-strip-debug-info"
      )
    )
  )
}
```

Error:

```
firtool returned a non-zero exit code. Note that this version of Chisel (7.6.0) was published against firtool version 1.138.0.
------------------------------------------------------------------------------
ExitCode:
1
STDOUT:

STDERR:
/Users/schuylereldridge/repos/github.com/seldridge/scala-snippets/Foo.scala:12:2: error: 'firrtl.module' op either contains layerblocks or has at least one instance that is or contains a Grand Central companion or layerblocks
@instantiable
 ^
/Users/schuylereldridge/repos/github.com/seldridge/scala-snippets/Foo.scala:12:2: note: see current operation: 
"firrtl.module"() <{annotations = [], convention = #firrtl<convention internal>, domainInfo = [], layers = [], portAnnotations = [], portDirections = array<i1: false, false, false>, portLocations = [loc("/Users/schuylereldridge/repos/github.com/seldridge/scala-snippets/ankit.scala":12:2), loc("/Users/schuylereldridge/repos/github.com/seldridge/scala-snippets/ankit.scala":12:2), loc("/Users/schuylereldridge/repos/github.com/seldridge/scala-snippets/ankit.scala":15:24)], portNames = ["clock", "reset", "in"], portSymbols = [], portTypes = [!firrtl.clock, !firrtl.reset, !firrtl.uint<1>], sym_name = "Bar"}> ({
^bb0(%arg0: !firrtl.clock, %arg1: !firrtl.reset, %arg2: !firrtl.uint<1>):
  "firrtl.skip"() : () -> ()
  "firrtl.layerblock"() <{layerName = @Verification}> ({
    "firrtl.layerblock"() <{layerName = @Verification::@Assert}> ({
      %0 = "firrtl.wire"() <{annotations = [], name = "x", nameKind = #firrtl<name_kind interesting_name>}> : () -> !firrtl.uint<1>
      %1 = "firrtl.invalidvalue"() : () -> !firrtl.uint<1>
      "firrtl.matchingconnect"(%0, %1) : (!firrtl.uint<1>, !firrtl.uint<1>) -> ()
    }) : () -> ()
  }) : () -> ()
}) {sym_visibility = "private"} : () -> ()
/Users/schuylereldridge/repos/github.com/seldridge/scala-snippets/Foo.scala:16:43: note: illegal layerblock here
  layer.block(layers.Verification.Assert) {
                                          ^
/Users/schuylereldridge/repos/github.com/seldridge/scala-snippets/Foo.scala:16:43: note: illegal layerblock here
/Users/schuylereldridge/repos/github.com/seldridge/scala-snippets/Foo.scala:26:18: note: illegal instantiation under a layerblock here
      Instantiate(new Bar)
```

### PR DESCRIPTION
**Pull request by seldridge**
Extend the Instantiate cache key to track if the instantiation is in an
`elideBlocks` scope.  This fixes a bug where an `Instantiate` call inside
an `elideBlocks` scope will instantiate a module which has layer
blocks (and defeat the intent of using `elideBlocks`).

Fixes #5138.

#### Release Notes

Fix a bug where the `elideBlocks` API would not strip layer blocks from modules inside it that used the `Instantiate` API.

### CODE REVIEW

File: src/test/scala-2/chiselTests/experimental/hierarchy/InstantiateSpec.scala [hunk 1]
```diff
@@ -518,6 +525,38 @@ class InstantiateSpec extends AnyFunSpec with Matchers with FileCheck {
...
+      }
+
+      emitCHIRRTL(new Foo).fileCheck()(
+        """|CHECK-COUNT-3: module
+           |CHECK-NOT:     module
+           |""".stripMargin
+      )
+    }
+
+    it("should not create a new instance for two instances both under an 'elideBlocks' scope") {
```
Comment (dtzSiFive) [inline src/test/scala-2/chiselTests/experimental/hierarchy/InstantiateSpec.scala]:
```suggestion
    it("should not create a new module for two instances both under an 'elideBlocks' scope") {
```
?

Comment (seldridge) [reply src/test/scala-2/chiselTests/experimental/hierarchy/InstantiateSpec.scala]: Good thought. Fixed in: a8d8a6089
