### PR TITLE
Bundles can no longer be instantiated with bound hardware

### LINKED ISSUE #1894: Autoclonetype 2 supports bound hardware as fields of Bundles
h/t @johnsbrew for reporting this in https://github.com/chipsalliance/chisel3/issues/1890

**Type of issue**: bug report

**Impact**: no functional change

**Development Phase**: request

**Other information**
 

**If the current behavior is a bug, please provide the steps to reproduce the problem:**

See https://scastie.scala-lang.org/DOeXfeVUQWiRcnmeB0JstQ

**What is the current behavior?**
The following works
```scala
class MyBundle(val foo: UInt) extends Bundle

class Example extends MultiIOModule {
  val in  = IO(Input(new MyBundle(123.U))) // This should error
  val out = IO(Output(new MyBundle(UInt(8.W))))

  out := in
}
```

**What is the expected behavior?**

This should give an error

### PR DESCRIPTION
**Pull request by jared-barocsi**
### Contributor Checklist

- [x] Did you add Scaladoc to every public function/method?
- [x] Did you add at least one test demonstrating the PR?
- [x] Did you delete any extraneous printlns/debugging code?
- [x] Did you specify the type of improvement?
- [x] Did you add appropriate documentation in `docs/src`?
- [x] Did you state the API impact?
- [x] Did you specify the code generation impact?
- [x] Did you request a desired merge strategy?
- [x] Did you add text to be included in the Release Notes for this change?

#### Type of Improvement

Bug fix

#### API Impact

Changes existing API: Code previously taking advantage of `Bundle`s with bound hardware elements will crash.

#### Backend Code Generation Impact

No impact

#### Desired Merge Strategy

Squash and merge

#### Release Notes
`Bundle`s can no longer be instantiated with value bindings or bound hardware. Fixes #1894

### Reviewer Checklist (only modified by reviewer)
- [ ] Did you add the appropriate labels?
- [ ] Did you mark the proper milestone (3.2.x, 3.3.x, 3.4.x, 3.5.0) ?
- [ ] Did you review?
- [ ] Did you check whether all relevant Contributor checkboxes have been checked?
- [ ] Did you mark as `Please Merge`?

### CODE REVIEW

**Comment by jackkoenig** [comment]
I've marked this `API Modification` because (as the removed test indicates), thing that used to "work" no longer do. That being said, I would argue this was an API hole, not a feature, since only very specific things worked and otherwise you usually got an error (rebinding if you passed such a Bundle to a binding op).

File: src/test/scala/chiselTests/BundleSpec.scala [hunk 1]
```diff
@@ -142,7 +153,11 @@ class BundleSpec extends ChiselFlatSpec with BundleSpecUtils with Utils {
...
 
-  "Bound Data" should "have priority in setting ref over unbound Data" in {
+  /**
+   * Broken in Chisel 3.5
+   * Bundles should not be able to be instantiated using any kind of bound hardware.
+   */
+  /*"Bound Data" should "have priority in setting ref over unbound Data" in {
     class MyModule extends RawModule {
       val foo = IO(new Bundle {
         val x = Output(UInt(8.W))
```
Comment (jackkoenig) [inline src/test/scala/chiselTests/BundleSpec.scala:163]: Better to delete the test than comment it out

File: core/src/main/scala/chisel3/Aggregate.scala [hunk 2]
```diff
@@ -963,6 +963,9 @@ abstract class Bundle(implicit compileOptions: CompileOptions) extends Record {
     for (m <- getPublicFields(classOf[Bundle])) {
       getBundleField(m) match {
         case Some(d: Data) =>
+          if (!d.binding.isEmpty)
+            throwException(s"Bundle can only take type elements (got value binding on '${m.getName()}')")
+
```
Comment (jackkoenig) [inline core/src/main/scala/chisel3/Aggregate.scala:968]:
```suggestion
          if (d.binding.nonEmpty) {
            throwException(s"Bundle can only take type elements (got value binding on '${m.getName()}')")
          }

```
Very much a nit but generally prefer `.nonEmpty` to `!_.isEmpty`, also, best to have the curly braces to avoid issues like the "goto fail" bug.

**Review by jackkoenig — COMMENTED** [review]
Generally looks good, a couple of minor suggestions.

File: core/src/main/scala/chisel3/Aggregate.scala [hunk 3]
```diff
@@ -963,6 +963,10 @@ abstract class Bundle(implicit compileOptions: CompileOptions) extends Record {
     for (m <- getPublicFields(classOf[Bundle])) {
       getBundleField(m) match {
         case Some(d: Data) =>
+          if (d.binding.nonEmpty) {
+            throwException(s"Bundle can only take type elements (got value binding '$d' on '${m.getName()}')")
+          }
```
Comment (sequencer) [inline core/src/main/scala/chisel3/Aggregate.scala:968]: Just another idea, maybe `requireIsChiselType` can catch this?

Comment (jackkoenig) [reply core/src/main/scala/chisel3/Aggregate.scala:968]: I think this suggestion conveys the intent a little more clearly.

File: src/test/scala/chiselTests/BundleSpec.scala [hunk 4]
```diff
@@ -129,6 +129,17 @@ class BundleSpec extends ChiselFlatSpec with BundleSpecUtils with Utils {
...
+    (the[ChiselException] thrownBy extractCause[ChiselException] {
+      ChiselStage.elaborate { new Module {
+        class MyBundle(val foo: UInt) extends Bundle
+        val in  = IO(Input(new MyBundle(123.U))) // This should error: value passed in instead of type
+        val out = IO(Output(new MyBundle(UInt(8.W))))
+
+        out := in
+      } }
+    }).getMessage should include("got value binding")
+  }
```
Comment (jackkoenig) [inline src/test/scala/chiselTests/BundleSpec.scala:142]: It's possible (but I'm not certain), that children of unbound aggregates still get their binding set to 
It'd be good to add 1 extra test  for a bound aggregate getting passed
```suggestion
  "Bundles" should "not have bound hardware" in {
    (the[ChiselException] thrownBy extractCause[ChiselException] {
      ChiselStage.elaborate { new Module {
        class MyBundle(val foo: UInt) extends Bundle
        val in  = IO(Input(new MyBundle(123.U))) // This should error: value passed in instead of type
        val out = IO(Output(new MyBundle(UInt(8.W))))

        out := in
      } }
    }).getMessage should include("got value binding")
    (the[ChiselException] thrownBy extractCause[ChiselException] {
      ChiselStage.elaborate { new Module {
        class MyBundle(val foo: UInt) extends Bundle
        val out = IO(Output(Vec(2, UInt(8.W))
        val in  = IO(Input(new MyBundle(out(0))) // This should error: value passed in instead of type

        out := in
      } }
    }).getMessage should include("got value binding")
  }
```

**Review by jackkoenig — APPROVED** [review]
