### PR TITLE
Fix stack trace trimming across Driver/ChiselStage

### LINKED ISSUE #1763: Stacktrace not trimmed or trimmed stacktrace ruined by additionnal full stacktrace
**Type of issue**: bug report
**Impact**: no functional change
**Development Phase**: request

**Other information**

Although chisel does a great job at trimming stack trace, when throwing an exception during chisel elaboration, `firrtl.options.StageError` still does (additionally) throw the whole stack trace.
While I do understand it remains very convenient for internal debug purpose, it is quite a pain because the beautiful trimmed stack-trace is hidden from user.

**If the current behavior is a bug, please provide the steps to reproduce the problem:**
Note that the  additional function & custom Exception are not required to demonstrate the behaviour.
There are here only to add some user-space call in the stacktrace.

```scala
import chisel3._
import chisel3.stage.ChiselStage

case class UserException(msg: String) extends Exception(msg)

class HwClass(doThrow: Boolean = false) extends MultiIOModule {
  val in = IO(Input(Bool()))
  val out = IO(Output(Bool()))
  
  def f(b: Bool): Bool = {
    if(doThrow) throw UserException("User error message")
    b
  }
  
  out := f(in)
}

object SimpleExceptionIssue extends App {
  (new ChiselStage).emitVerilog(new HwClass(doThrow = true))
}

```
**What is the current behavior?**

```
[info] [0,003] Elaborating design...
[error] <user error message>
[error] 	...
[error] 	at <user code call>
// <potentially many more lines of user calls> //
[error] 	at <user code call>
[error] 	... (Stack trace trimmed to user code only, rerun with --full-stacktrace if you wish to see the full stack trace)
[error] (run-main-4c) firrtl.options.StageError:
[error] firrtl.options.StageError:
[error] 	at chisel3.stage.ChiselStage.run(ChiselStage.scala:60)
[error] 	at firrtl.options.Stage$$anon$1.transform(Stage.scala:43)
[error] 	at firrtl.options.Stage$$anon$1.transform(Stage.scala:43)
[error] 	at firrtl.options.phases.DeletedWrapper.internalTransform(DeletedWrapper.scala:38)
[error] 	at firrtl.options.phases.DeletedWrapper.internalTransform(DeletedWrapper.scala:15)
[error] 	at firrtl.options.Translator.transform(Phase.scala:248)
[error] 	at firrtl.options.Translator.transform$(Phase.scala:248)
[error] 	at firrtl.options.phases.DeletedWrapper.transform(DeletedWrapper.scala:15)
[error] 	at firrtl.options.Stage.$anonfun$transform$5(Stage.scala:47)
[error] 	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:126)
[error] 	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:122)
[error] 	at scala.collection.immutable.List.foldLeft(List.scala:91)
[error] 	at firrtl.options.Stage.$anonfun$transform$3(Stage.scala:47)
[error] 	at logger.Logger$.$anonfun$makeScope$2(Logger.scala:166)
[error] 	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
[error] 	at logger.Logger$.makeScope(Logger.scala:164)
[error] 	at firrtl.options.Stage.transform(Stage.scala:47)
[error] 	at firrtl.options.Stage.execute(Stage.scala:58)
[error] 	at chisel3.stage.ChiselStage.emitVerilog(ChiselStage.scala:117)
[error] 	at <user main code for calling chisel call>
[error] 	at <user main code for calling chisel call>
[error] 	at <user main code for calling chisel call>
[error] 	at <user main code for calling chisel call>
[error] 	at scala.Function0.apply$mcV$sp(Function0.scala:39)
[error] 	at scala.Function0.apply$mcV$sp$(Function0.scala:39)
[error] 	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
[error] 	at scala.App.$anonfun$main$1$adapted(App.scala:80)
[error] 	at scala.collection.immutable.List.foreach(List.scala:431)
[error] 	at scala.App.main(App.scala:80)
[error] 	at scala.App.main$(App.scala:78)
[error] 	at <user main code for calling chisel call>
[error] 	at <user main code for calling chisel call>
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
[error] Caused by: chisel3.internal.ChiselException: Exception thrown when elaborating ChiselGeneratorAnnotation
[error] 	at chisel3.stage.ChiselGeneratorAnnotation.elaborate(ChiselAnnotations.scala:65)
[error] 	at chisel3.stage.phases.Elaborate.$anonfun$transform$1(Elaborate.scala:24)
[error] 	at scala.collection.immutable.List.flatMap(List.scala:366)
[error] 	at chisel3.stage.phases.Elaborate.transform(Elaborate.scala:23)
[error] 	at chisel3.stage.phases.Elaborate.transform(Elaborate.scala:16)
[error] 	at firrtl.options.phases.DeletedWrapper.internalTransform(DeletedWrapper.scala:38)
[error] 	at firrtl.options.phases.DeletedWrapper.internalTransform(DeletedWrapper.scala:15)
[error] 	at firrtl.options.Translator.transform(Phase.scala:248)
[error] 	at firrtl.options.Translator.transform$(Phase.scala:248)
[error] 	at firrtl.options.phases.DeletedWrapper.transform(DeletedWrapper.scala:15)
[error] 	at firrtl.options.DependencyManager.$anonfun$transform$3(DependencyManager.scala:278)
[error] 	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:126)
[error] 	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:122)
[error] 	at scala.collection.immutable.List.foldLeft(List.scala:91)
[error] 	at firrtl.options.DependencyManager.transform(DependencyManager.scala:269)
[error] 	at firrtl.options.DependencyManager.transform$(DependencyManager.scala:255)
[error] 	at firrtl.options.PhaseManager.transform(DependencyManager.scala:436)
[error] 	at chisel3.stage.ChiselStage.run(ChiselStage.scala:46)
[error] 	at firrtl.options.Stage$$anon$1.transform(Stage.scala:43)
[error] 	at firrtl.options.Stage$$anon$1.transform(Stage.scala:43)
[error] 	at firrtl.options.phases.DeletedWrapper.internalTransform(DeletedWrapper.scala:38)
[error] 	at firrtl.options.phases.DeletedWrapper.internalTransform(DeletedWrapper.scala:15)
[error] 	at firrtl.options.Translator.transform(Phase.scala:248)
[error] 	at firrtl.options.Translator.transform$(Phase.scala:248)
[error] 	at firrtl.options.phases.DeletedWrapper.transform(DeletedWrapper.scala:15)
[error] 	at firrtl.options.Stage.$anonfun$transform$5(Stage.scala:47)
[error] 	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:126)
[error] 	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:122)
[error] 	at scala.collection.immutable.List.foldLeft(List.scala:91)
[error] 	at firrtl.options.Stage.$anonfun$transform$3(Stage.scala:47)
[error] 	at logger.Logger$.$anonfun$makeScope$2(Logger.scala:166)
[error] 	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
[error] 	at logger.Logger$.makeScope(Logger.scala:164)
[error] 	at firrtl.options.Stage.transform(Stage.scala:47)
[error] 	at firrtl.options.Stage.execute(Stage.scala:58)
[error] 	at chisel3.stage.ChiselStage.emitVerilog(ChiselStage.scala:117)
[error] 	at <user main code for calling chisel call>
[error] 	at <user main code for calling chisel call>
[error] 	at <user main code for calling chisel call>
[error] 	at <user main code for calling chisel call>
[error] 	at scala.Function0.apply$mcV$sp(Function0.scala:39)
[error] 	at scala.Function0.apply$mcV$sp$(Function0.scala:39)
[error] 	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
[error] 	at scala.App.$anonfun$main$1$adapted(App.scala:80)
[error] 	at scala.collection.immutable.List.foreach(List.scala:431)
[error] 	at scala.App.main(App.scala:80)
[error] 	at scala.App.main$(App.scala:78)
[error] 	at <user main code for calling chisel call>
[error] 	at <user main code for calling chisel call>
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
[error] Caused by: <user error message>
[error] 	at <user code call>
// <potentially many more lines of user calls> //
[error] 	at <user code call>
[error] 	at chisel3.Module$.do_apply(Module.scala:54)
[error] 	at chisel3.stage.ChiselGeneratorAnnotation.$anonfun$elaborate$1(ChiselAnnotations.scala:60)
[error] 	at chisel3.internal.Builder$.$anonfun$build$1(Builder.scala:642)
[error] 	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
[error] 	at chisel3.internal.Builder$.build(Builder.scala:639)
[error] 	at chisel3.internal.Builder$.build(Builder.scala:635)
[error] 	at chisel3.stage.ChiselGeneratorAnnotation.elaborate(ChiselAnnotations.scala:60)
[error] 	at chisel3.stage.phases.Elaborate.$anonfun$transform$1(Elaborate.scala:24)
[error] 	at scala.collection.immutable.List.flatMap(List.scala:366)
[error] 	at chisel3.stage.phases.Elaborate.transform(Elaborate.scala:23)
[error] 	at chisel3.stage.phases.Elaborate.transform(Elaborate.scala:16)
[error] 	at firrtl.options.phases.DeletedWrapper.internalTransform(DeletedWrapper.scala:38)
[error] 	at firrtl.options.phases.DeletedWrapper.internalTransform(DeletedWrapper.scala:15)
[error] 	at firrtl.options.Translator.transform(Phase.scala:248)
[error] 	at firrtl.options.Translator.transform$(Phase.scala:248)
[error] 	at firrtl.options.phases.DeletedWrapper.transform(DeletedWrapper.scala:15)
[error] 	at firrtl.options.DependencyManager.$anonfun$transform$3(DependencyManager.scala:278)
[error] 	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:126)
[error] 	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:122)
[error] 	at scala.collection.immutable.List.foldLeft(List.scala:91)
[error] 	at firrtl.options.DependencyManager.transform(DependencyManager.scala:269)
[error] 	at firrtl.options.DependencyManager.transform$(DependencyManager.scala:255)
[error] 	at firrtl.options.PhaseManager.transform(DependencyManager.scala:436)
[error] 	at chisel3.stage.ChiselStage.run(ChiselStage.scala:46)
[error] 	at firrtl.options.Stage$$anon$1.transform(Stage.scala:43)
[error] 	at firrtl.options.Stage$$anon$1.transform(Stage.scala:43)
[error] 	at firrtl.options.phases.DeletedWrapper.internalTransform(DeletedWrapper.scala:38)
[error] 	at firrtl.options.phases.DeletedWrapper.internalTransform(DeletedWrapper.scala:15)
[error] 	at firrtl.options.Translator.transform(Phase.scala:248)
[error] 	at firrtl.options.Translator.transform$(Phase.scala:248)
[error] 	at firrtl.options.phases.DeletedWrapper.transform(DeletedWrapper.scala:15)
[error] 	at firrtl.options.Stage.$anonfun$transform$5(Stage.scala:47)
[error] 	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:126)
[error] 	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:122)
[error] 	at scala.collection.immutable.List.foldLeft(List.scala:91)
[error] 	at firrtl.options.Stage.$anonfun$transform$3(Stage.scala:47)
[error] 	at logger.Logger$.$anonfun$makeScope$2(Logger.scala:166)
[error] 	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
[error] 	at logger.Logger$.makeScope(Logger.scala:164)
[error] 	at firrtl.options.Stage.transform(Stage.scala:47)
[error] 	at firrtl.options.Stage.execute(Stage.scala:58)
[error] 	at chisel3.stage.ChiselStage.emitVerilog(ChiselStage.scala:117)
[error] 	at <user main code for calling chisel call>
[error] 	at <user main code for calling chisel call>
[error] 	at <user main code for calling chisel call>
[error] 	at <user main code for calling chisel call>
[error] 	at scala.Function0.apply$mcV$sp(Function0.scala:39)
[error] 	at scala.Function0.apply$mcV$sp$(Function0.scala:39)
[error] 	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
[error] 	at scala.App.$anonfun$main$1$adapted(App.scala:80)
[error] 	at scala.collection.immutable.List.foreach(List.scala:431)
[error] 	at scala.App.main(App.scala:80)
[error] 	at scala.App.main$(App.scala:78)
[error] 	at <user main code for calling chisel call>
[error] 	at <user main code for calling chisel call>
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
[error] stack trace is suppressed; run last Compile / bgRunMain for the full output
[error] Nonzero exit code: 1
[error] (Compile / runMain) Nonzero exit code: 1
[error] Total time: 7 s, completed 27 janv. 2021 à 11:19:35

```

Note that this becomes even worse when using `object ChiselStage` rather than `class ChiselStage` such as

```scala
object SimpleExceptionIssue extends App {
  ChiselStage.emitVerilog(new HwClass(doThrow = true))
}
```

In such a case you don't even get the trimmed stacktrace and the user error message is hidden as a cause:

```
[info] running SimpleExceptionIssue
[info] [0,017] Elaborating design...
[error] (run-main-5f) chisel3.internal.ChiselException: Exception thrown when elaborating ChiselGeneratorAnnotation
[error] chisel3.internal.ChiselException: Exception thrown when elaborating ChiselGeneratorAnnotation
[error] 	at chisel3.stage.ChiselGeneratorAnnotation.elaborate(ChiselAnnotations.scala:65)
[error] 	at chisel3.stage.phases.Elaborate.$anonfun$transform$1(Elaborate.scala:24)
[error] 	at scala.collection.immutable.List.flatMap(List.scala:366)
[error] 	at chisel3.stage.phases.Elaborate.transform(Elaborate.scala:23)
[error] 	at chisel3.stage.phases.Elaborate.transform(Elaborate.scala:16)
[error] 	at firrtl.options.DependencyManager.$anonfun$transform$3(DependencyManager.scala:278)
[error] 	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:126)
[error] 	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:122)
[error] 	at scala.collection.immutable.List.foldLeft(List.scala:91)
[error] 	at firrtl.options.DependencyManager.transform(DependencyManager.scala:269)
[error] 	at firrtl.options.DependencyManager.transform$(DependencyManager.scala:255)
[error] 	at firrtl.options.PhaseManager.transform(DependencyManager.scala:436)
[error] 	at chisel3.stage.ChiselStage$.emitVerilog(ChiselStage.scala:236)
[error] 	at fpgaTests.utils.SimpleExceptionIssue$.delayedEndpoint$fpgaTests$utils$SimpleExceptionIssue$1(PlayGroundSpec.scala:202)
[error] 	at fpgaTests.utils.SimpleExceptionIssue$delayedInit$body.apply(PlayGroundSpec.scala:200)
[error] 	at scala.Function0.apply$mcV$sp(Function0.scala:39)
[error] 	at scala.Function0.apply$mcV$sp$(Function0.scala:39)
[error] 	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
[error] 	at scala.App.$anonfun$main$1$adapted(App.scala:80)
[error] 	at scala.collection.immutable.List.foreach(List.scala:431)
[error] 	at scala.App.main(App.scala:80)
[error] 	at scala.App.main$(App.scala:78)
[error] 	at fpgaTests.utils.SimpleExceptionIssue$.main(PlayGroundSpec.scala:200)
[error] 	at fpgaTests.utils.SimpleExceptionIssue.main(PlayGroundSpec.scala)
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
[error] Caused by: fpgaTests.utils.UserException: User error message
[error] 	at fpgaTests.utils.HwClass.f(PlayGroundSpec.scala:192)
[error] 	at fpgaTests.utils.HwClass.$anonfun$new$8(PlayGroundSpec.scala:196)
[error] 	at chisel3.Data.$anonfun$$colon$eq$1(Data.scala:524)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error] 	at chisel3.internal.prefix$.apply(prefix.scala:32)
[error] 	at chisel3.Data.$colon$eq(Data.scala:524)
[error] 	at fpgaTests.utils.HwClass.<init>(PlayGroundSpec.scala:196)
[error] 	at fpgaTests.utils.SimpleExceptionIssue$.$anonfun$new$9(PlayGroundSpec.scala:202)
[error] 	at chisel3.Module$.do_apply(Module.scala:54)
[error] 	at chisel3.stage.ChiselGeneratorAnnotation.$anonfun$elaborate$1(ChiselAnnotations.scala:60)
[error] 	at chisel3.internal.Builder$.$anonfun$build$1(Builder.scala:642)
[error] 	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
[error] 	at chisel3.internal.Builder$.build(Builder.scala:639)
[error] 	at chisel3.internal.Builder$.build(Builder.scala:635)
[error] 	at chisel3.stage.ChiselGeneratorAnnotation.elaborate(ChiselAnnotations.scala:60)
[error] 	at chisel3.stage.phases.Elaborate.$anonfun$transform$1(Elaborate.scala:24)
[error] 	at scala.collection.immutable.List.flatMap(List.scala:366)
[error] 	at chisel3.stage.phases.Elaborate.transform(Elaborate.scala:23)
[error] 	at chisel3.stage.phases.Elaborate.transform(Elaborate.scala:16)
[error] 	at firrtl.options.DependencyManager.$anonfun$transform$3(DependencyManager.scala:278)
[error] 	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:126)
[error] 	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:122)
[error] 	at scala.collection.immutable.List.foldLeft(List.scala:91)
[error] 	at firrtl.options.DependencyManager.transform(DependencyManager.scala:269)
[error] 	at firrtl.options.DependencyManager.transform$(DependencyManager.scala:255)
[error] 	at firrtl.options.PhaseManager.transform(DependencyManager.scala:436)
[error] 	at chisel3.stage.ChiselStage$.emitVerilog(ChiselStage.scala:236)
[error] 	at fpgaTests.utils.SimpleExceptionIssue$.delayedEndpoint$fpgaTests$utils$SimpleExceptionIssue$1(PlayGroundSpec.scala:202)
[error] 	at fpgaTests.utils.SimpleExceptionIssue$delayedInit$body.apply(PlayGroundSpec.scala:200)
[error] 	at scala.Function0.apply$mcV$sp(Function0.scala:39)
[error] 	at scala.Function0.apply$mcV$sp$(Function0.scala:39)
[error] 	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
[error] 	at scala.App.$anonfun$main$1$adapted(App.scala:80)
[error] 	at scala.collection.immutable.List.foreach(List.scala:431)
[error] 	at scala.App.main(App.scala:80)
[error] 	at scala.App.main$(App.scala:78)
[error] 	at fpgaTests.utils.SimpleExceptionIssue$.main(PlayGroundSpec.scala:200)
[error] 	at fpgaTests.utils.SimpleExceptionIssue.main(PlayGroundSpec.scala)
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
[error] stack trace is suppressed; run last Test / bgRunMain for the full output
[error] Nonzero exit code: 1
[error] (Test / runMain) Nonzero exit code: 1
[error] Total time: 26 s, completed 29 janv. 2021 à 10:18:31
```
**What is the expected behavior?**

```
[info] [0,003] Elaborating design...
[error] <user error message>
[error] 	...
[error] 	at <user code call>
// <potentially many more lines of user calls> //
[error] 	at <user code call>
[error] 	... (Stack trace trimmed to user code only, rerun with --full-stacktrace if you wish to see the full stack trace)
[error] stack trace is suppressed; run last Compile / bgRunMain for the full output
[error] Nonzero exit code: 1
[error] (Compile / runMain) Nonzero exit code: 1
[error] Total time: 7 s, completed 27 janv. 2021 à 11:19:35
```

**Please tell us about your environment:**
    - version: `3.4.1`
    - OS: `Darwin 17.7.0 Darwin Kernel Version 17.7.0: Fri Oct 30 13:34:27 PDT 2020; root:xnu-4570.71.82.8~1/RELEASE_X86_64 x86_64`

**What is the use case for changing the behavior?**
Nicer errors = happier users

### Issue summary
- with ChiselStage.emitVerilog => stacktrace is not trimmed and is awful (user error hidden right in the middle)
- with (new ChiselStage).emitVerilog => stacktrace is trimmed but then the whole stacktrace is appended
- underlying issue: difference of behaviour between `object` & `class ChiselStage`
    - `object ChiselStage` relies on `PhaseManager`
    - `class ChiselStage` relies on `firrtl.options.Stage` (who is actually the culprit for throwing the additional stacktrace)

For me `ChiselStage` (and the entire Stage/Phase API) is one of the most obscure piece of code of the chisel/firrtl ecosystem although, several times, I spend hours (if not days) digging into it just to be able to customize our build flow a little bit...
And here we have... a companion object not even using its associated class but both somehow relying on the same underlying Stage/Phase API, with roughly the same result... but not quite!

There is a really serious underlying concern about trust here: 
- how can we expect the generated verilog to be same in both case? 
- Can we expect custom transforms to be applied in both case? In the same order? 
- It's a real nightmare.
 
When I first posted about this issue in https://github.com/chipsalliance/firrtl/issues/974 I thought I was looking for a quick fix... but as soon as `Stage/Phase API` gets involved, suprises occur and everything gets cumbersome... 
 
So I would be happy to help about the stacktrace issue, but this entire file https://github.com/chipsalliance/chisel3/blob/master/src/main/scala/chisel3/stage/ChiselStage.scala needs some uniformization first... and on that one I would like to request help from @seldridge or @jackkoenig  ?

### PR DESCRIPTION
**Pull request by seldridge**
Fix bug in stack trace trimming behavior. Now, the following is what
happens:
    
1. The Builder, if catching accumulated errors, will now throw a
   ChiselException with a Scala-trimmed Stack trace. Previously, this
   would throw the full excpetion.
2. The Elaborate phase handles stack trace trimming. By default, any
   Throwable thrown during elaboration will have its stack
   trace *mutably* trimmed and is rethrown. A logger.error is printed
   stating that there was an error during elaboration and how the user
   can turn on the full stack trace. If the --full-stacktrace option
   is on, then the Throwable is not caught and only the first
   logger.error (saying that elaboration failed) will be printed.
3. ChiselStage (the class), ChiselStage$ (the object), and ChiselMain
   all inherit the behavior of (2).
    
Mutable stack trace trimming behavior is moved into an implicit
class (previously this was defined on ChiselException only) so this
can be applied to any Throwable.
    
No StageErrors are now thrown anymore. However, StageErrors may still
be caught by ChiselMain (since it is a StageMain).
    
Testing is added for ChiselMain, ChiselStage, and ChiselStage$ to test
all this behavior.

Fixes #1763. (I think...)

### Contributor Checklist

- [ ] Did you add Scaladoc to every public function/method?
- [x] Did you add at least one test demonstrating the PR?
- [x] Did you delete any extraneous printlns/debugging code?
- [x] Did you specify the type of improvement?
- [x] Did you add appropriate documentation in `docs/src`?
- [x] Did you state the API impact?
- [x] Did you specify the code generation impact?
- [x] Did you request a desired merge strategy?
- [x] Did you add text to be included in the Release Notes for this change?

#### Type of Improvement

- bug fix

- code refactoring

#### API Impact

None for actual user-facing API. Some exception behavior is changed.

#### Backend Code Generation Impact

None.

#### Desired Merge Strategy

- Squash: The PR will be squashed and merged (choose this if you have no preference.

### Reviewer Checklist (only modified by reviewer)
- [ ] Did you add the appropriate labels?
- [ ] Did you mark the proper milestone (3.2.x, 3.3.x, 3.4.0, 3.5.0) ?
- [ ] Did you review?
- [ ] Did you check whether all relevant Contributor checkboxes have been checked?
- [ ] Did you mark as `Please Merge`?

### CODE REVIEW

File: src/main/scala/chisel3/Driver.scala [hunk 1]
```diff
@@ -241,10 +241,22 @@ object Driver extends BackendCompilationUtilities {
     val annosx = try {
       phases.foldLeft(annos)( (a, p) => p.transform(a) )
     } catch {
-      /* ChiselStage and FirrtlStage can throw StageError. Since Driver is not a StageMain, it cannot catch these. While
-       * Driver is deprecated and removed in 3.2.1+, the Driver catches all errors.
+      /* Catch all errors and show a fake stack trace. If the stack trace was minified elsewhere, e.g., in the Elaborate
+       * phase, then it will show up minified here. The Driver cannot fail for any reason. Instead, a
```
Comment (mwachs5) [inline src/main/scala/chisel3/Driver.scala:245]: what does "The Driver cannot fail for any reason" mean exactly? It is not allowed to throw any errors?

Comment (seldridge) [reply src/main/scala/chisel3/Driver.scala:245]: Bad language on my part. It's saying that the Driver will catch all exceptions.

Specifically, if any Throwable that happens while the Driver is running (elaboration, conversion, etc.), then the Driver will always catch this, print out a fake stake trace on stdout, and then return an `ExecutionFailure` result. The Driver can fail and this will be visible to the user on stdout and they can check that an `ExecutionFailure` was returned to know that it failed.

**Comment by jackkoenig** [comment]
Any Driver work here is going to conflict with https://github.com/chipsalliance/chisel3/pull/1730, any thoughts @seldridge and @sequencer?

**Comment by seldridge** [comment]
No real conflict as far as I'm concerned. If #1730 goes first, then this PR should drop it's Driver changes (because it doesn't exist). If this goes before #1730, then #1730 should still remove the driver.

**Comment by sequencer** [comment]
I think if Driver will be dropped at last. So let's get #1730 merged first?

File: core/src/main/scala/chisel3/internal/Error.scala [hunk 2]
```diff
@@ -5,7 +5,34 @@ package chisel3.internal
...
+
+  implicit class ThrowableHelpers(a: Throwable) {
+
+    /** Package names whose stack trace elements should be trimmed when generating a trimmed stack trace */
+    private val blacklistPackages: Set[String] = Set("chisel3", "scala", "java", "jdk", "sun", "sbt")
+
+    /** The object name of Chisel's internal `Builder`. Everything stack trace element after this will be trimmed. */
+    private val builderName: String = chisel3.internal.Builder.getClass.getName
+
+    def trimStackTraceToUserCode(blacklist: Set[String] = blacklistPackages, anchor: String = builderName): Unit = {
```
Comment (jackkoenig) [inline core/src/main/scala/chisel3/internal/Error.scala:18]:
```suggestion
    /** Package names whose stack trace elements should be trimmed when generating a trimmed stack trace */
    private val trimlistPackages: Set[String] = Set("chisel3", "scala", "java", "jdk", "sun", "sbt")

    /** The object name of Chisel's internal `Builder`. Everything stack trace element after this will be trimmed. */
    private val builderName: Option[String] = Some(chisel3.internal.Builder.getClass.getName)

    def trimStackTraceToUserCode(trimlist: Set[String] = trimlistPackages, anchor: Option[String] = builderName): Unit = {
```
Minor terminology suggestion and maybe making the `anchor` optional since it's possible one might not want an anchor.

Comment (seldridge) [reply core/src/main/scala/chisel3/internal/Error.scala]: Good idea. Fixed in the latest commit.

File: src/main/scala/chisel3/Driver.scala (hunk 1 above)
Comment (seldridge) [reply src/main/scala/chisel3/Driver.scala]: This is now irrelevant thanks to @sequencer's hard work on #1730.

**Comment by seldridge** [comment]
There are some weird interactions with capturing `stdout` and checking it seemingly having a weird interaction with the `Logger`. I'm also refactoring this so that it can be applied to the `master` branch and to `3.4.x`. (I was incorrect above, this needs to be backported so that we can fix this in 3.4.3.)

**Comment by seldridge** [comment]
Manual backport to 3.4.x is here: https://github.com/chipsalliance/chisel3/pull/1773.

File: core/src/main/scala/chisel3/internal/Error.scala [hunk 3]
```diff
@@ -5,12 +5,70 @@ package chisel3.internal
...
+          }
+        )
+      // Step 3: Remove elements from the bottom in the package trimlist
+        .andThen(_.dropWhile(inTrimlist))
+      // Step 4: Reverse back to the original order
+        .andThen(_.reverse.toArray)
+      // Step 5: Mutate the stack trace in this exception
+        .andThen(throwable.setStackTrace(_))
+        .apply(throwable.getStackTrace)
+    }
```
[the remark this answers is not in the document]
Comment (jackkoenig) [reply core/src/main/scala/chisel3/internal/Error.scala:58]: We could extend this trick to try to not do the `logger` stuff at all (which I think is a vast improvement over the status quo, but I don't love), instead embedding the message about `--full-stacktrace` in as a pseudo-StackTraceElement`:
```
[error] (run-main-14) chisel3.package$ExpectedHardwareException: bits operated on 'UInt' must be hardware, not a bare Chisel type. Perhaps you forgot to wrap it in Wire(_) or IO(_)?
[error] chisel3.package$ExpectedHardwareException: bits operated on 'UInt' must be hardware, not a bare Chisel type. Perhaps you forgot to wrap it in Wire(_) or IO(_)?
[error]         at ...()
[error]         at gcd.GCD.$anonfun$new$3(GCD.scala:24)
[error]         at chisel3.Data.$anonfun$$colon$eq$1(Data.scala:540)
[error]         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error]         at chisel3.internal.prefix$.apply(prefix.scala:32)
[error]         at chisel3.Data.$colon$eq(Data.scala:540)
[error]         at gcd.GCD.$anonfun$new$2(GCD.scala:24)
[error]         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error]         at chisel3.WhenContext.<init>(When.scala:124)
[error]         at chisel3.when$.apply(When.scala:31)
[error]         at gcd.GCD.<init>(GCD.scala:24)
[error]         at gcd.GCDMain$.$anonfun$new$12(GCD.scala:40)
[error]         at ...()
[error]         at ...(Stack trace trimmed to user code only. Rerun with --full-stacktrace to see the full stack trace)
```

File: src/main/scala/chisel3/stage/phases/Elaborate.scala [hunk 4]
```diff
@@ -21,8 +22,20 @@ class Elaborate extends Phase {
...
+      a.elaborate
+    } catch {
+      /* if any throwable comes back and we're in "stack trace trimming" mode, then print an error and trim the stack trace
+       */
+      case a: Throwable =>
+        logger.error("Error during elaboration!")
+        if (!view[ChiselOptions](annotations).printFullStackTrace) {
+          logger.error("Stack trace will be trimmed to user code only. Rerun with --full-stacktrace to see the full stack trace")
+          a.trimStackTraceToUserCode()
+        }
```
Comment (jackkoenig) [inline src/main/scala/chisel3/stage/phases/Elaborate.scala:35]: See comments above, I don't love the `logger.error` here, but this is still sooo much better than the status quo.

File: src/test/scala/chiselTests/stage/ChiselStageSpec.scala [hunk 5]
```diff
@@ -142,4 +146,54 @@ class ChiselStageSpec extends AnyFlatSpec with Matchers with Utils {
     exactly (1, order) should be (Dependency[chisel3.stage.phases.Elaborate])
   }
 
+  behavior of "ChiselStage$ exception handling"
+
+  it should "truncate a user exception" in {
+    info("A generic ChiselException was thrown, not the underlying java.lang.AssertionError")
+    val exception = intercept[java.lang.AssertionError] {
```
Comment (jackkoenig) [inline src/test/scala/chiselTests/stage/ChiselStageSpec.scala:153]: If this statement is true, then shouldn't you be intercepting a `ChiselException`?

**Review by jackkoenig — COMMENTED** [review]
This is fantastic, I have a few comments I'd like answered but the tests are great and I love the simplified and unified functionality

File: core/src/main/scala/chisel3/internal/Error.scala (hunk 3 above)
[the remark this answers is not in the document]
Comment (seldridge) [reply core/src/main/scala/chisel3/internal/Error.scala:58]: I'll update to this in a fixup commit.

File: src/main/scala/chisel3/stage/phases/Elaborate.scala (hunk 4 above)
Comment (seldridge) [reply src/main/scala/chisel3/stage/phases/Elaborate.scala:35]: Will drop the `--full-stacktrace` logger.error in a fixup commit. Were you talking about the `Error during elaboration`, too?

File: src/test/scala/chiselTests/stage/ChiselStageSpec.scala (hunk 5 above)
Comment (seldridge) [reply src/test/scala/chiselTests/stage/ChiselStageSpec.scala:153]: Yep, you're right. This was left over from an early iteration of this PR. Will fix in a fixup commit.

File: src/main/scala/chisel3/stage/phases/Elaborate.scala (hunk 4 above)
Comment (jackkoenig) [reply src/main/scala/chisel3/stage/phases/Elaborate.scala:35]: I feel less strongly about `Error during elaboration`. I'd probably drop it since an Exception is a pretty good indicator something went wrong, but if you'd rather keep it I think it's fine.

**Comment by seldridge** [comment]
Ready for re-review. Also, the backport (https://github.com/chipsalliance/chisel3/pull/1773) should be reviewed, too. I'm currently maintaining the backport and then cherry-picking onto master for this PR.

File: src/test/scala/chiselTests/stage/ChiselStageSpec.scala (hunk 5 above)
Comment (seldridge) [reply src/test/scala/chiselTests/stage/ChiselStageSpec.scala]: Fixed in the rebase.

File: src/main/scala/chisel3/stage/phases/Elaborate.scala (hunk 4 above)
Comment (seldridge) [reply src/main/scala/chisel3/stage/phases/Elaborate.scala]: Updated in rebase. Let me know if you want the earlier logger.error removed.

File: core/src/main/scala/chisel3/internal/Error.scala (hunk 3 above)
[the remark this answers is not in the document]
Comment (seldridge) [reply core/src/main/scala/chisel3/internal/Error.scala:70]: Fixed in the rebase. Output now looks like:

File: src/main/scala/chisel3/stage/phases/Elaborate.scala (hunk 4 above)
Comment (seldridge) [reply src/main/scala/chisel3/stage/phases/Elaborate.scala]: (GitHub didn't refresh for the above comment.) Changed in a fixup commit on both branches.

**Review by jackkoenig — APPROVED** [review]
LGTM! Nice work.

File: src/main/scala/chisel3/stage/phases/Elaborate.scala [hunk 6]
```diff
@@ -21,8 +22,18 @@ class Elaborate extends Phase {
...
 
   def transform(annotations: AnnotationSeq): AnnotationSeq = annotations.flatMap {
-    case a: ChiselGeneratorAnnotation => a.elaborate
-    case a                            => Some(a)
+    case a: ChiselGeneratorAnnotation => try {
+      a.elaborate
+    } catch {
+      /* if any throwable comes back and we're in "stack trace trimming" mode, then print an error and trim the stack trace
+       */
+      case a: Throwable =>
```
Comment (jackkoenig) [inline src/main/scala/chisel3/stage/phases/Elaborate.scala:30]: I guess the `NonFatal` comment applies here too then

Comment (seldridge) [reply src/main/scala/chisel3/stage/phases/Elaborate.scala]: Fixed in the rebase.

File: src/main/scala/chisel3/Driver.scala (hunk 1 above)
Comment (athurwo) [reply src/main/scala/chisel3/Driver.scala]: not resolve, when git clone new code, then run "sbt compile", happen a error 
"src/main/scala/chisel3/Driver.scala:54:12: object Driver is not a member of package firrtl
[error]     firrtl.Driver.execute(optionsManager) match {"

`trait BackendCompilationUtilities extends FirrtlBackendCompilationUtilities {
  /** Compile Chirrtl to Verilog by invoking Firrtl inside the same JVM
    *
    * @param prefix basename of the file
    * @param dir    directory where file lives
    * @return       true if compiler completed successfully
    */
  def compileFirrtlToVerilog(prefix: String, dir: File): Boolean = {
    val optionsManager = new ExecutionOptionsManager("chisel3") with HasChiselExecutionOptions with HasFirrtlOptions {
      commonOptions = CommonOptions(topName = prefix, targetDirName = dir.getAbsolutePath)
      firrtlOptions = FirrtlExecutionOptions(compilerName = "verilog")
    }

    firrtl.Driver.execute(optionsManager,) match {
      case _: FirrtlExecutionSuccess => true
      case _: FirrtlExecutionFailure => false
    }
  }
}
`
but Driver had be removed.  what can I do for running "sbt compile" successfully.
