### PR TITLE
catch None.get in BitPat.apply(x: UInt): BitPat

### LINKED ISSUE #2268: BitPat is not happy with Cat(someEnum.asUInt, someBool.B)
https://scastie.scala-lang.org/fLovomFGRUaMML8MvEIBwA
```
import chisel3._
import chisel3.util._
import chisel3.experimental.ChiselEnum

object TestEnum extends ChiselEnum {
  val s0 = Value
}

class Example extends Module {
  val a = BitPat(Cat(TestEnum.s0.asUInt, true.B))
}

println(getVerilogString(new Example))
```
doesn't work.

**Type of issue**: bug report

**Impact**: unknown

**Development Phase**: request

**Other information**
**If the current behavior is a bug, please provide the steps to reproduce the problem:**

**What is the current behavior?**
```
java.util.NoSuchElementException: None.get
	at ... ()
	at Playground$Example.<init>(main.scala:12)
	at Playground$$anonfun$2.apply(main.scala:15)
	at Playground$$anonfun$2.apply(main.scala:15)
	at ... ()
	at ... (Stack trace trimmed to user code only. Rerun with --full-stacktrace to see the full stack trace)
}
```

**What is the expected behavior?**
I think this should work?

**Please tell us about your environment:**
Chisel 3.5-SNAPSHOT
**What is the use case for changing the behavior?**

### PR DESCRIPTION
**Pull request by sequencer**
Resolves #2268, thanks @Tang-Haojin 
### Contributor Checklist

- [ ] Did you add Scaladoc to every public function/method?
- [x] Did you add at least one test demonstrating the PR?
- [x] Did you delete any extraneous printlns/debugging code?
- [x] Did you specify the type of improvement?
- [ ] Did you add appropriate documentation in `docs/src`?
- [x] Did you state the API impact?
- [x] Did you specify the code generation impact?
- [x] Did you request a desired merge strategy?
- [x] Did you add text to be included in the Release Notes for this change?

#### Type of Improvement
- bug fix

#### API Impact
None

#### Backend Code Generation Impact
None

#### Desired Merge Strategy
- Rebase: You will rebase the PR onto master and it will be merged with a merge commit.

#### Release Notes
None

### Reviewer Checklist (only modified by reviewer)
- [ ] Did you add the appropriate labels?
- [ ] Did you mark the proper milestone (Bug fix: `3.3.x`, [small] API extension: `3.4.x`, API modification or big change: `3.5.0`)?
- [ ] Did you review?
- [ ] Did you check whether all relevant Contributor checkboxes have been checked?
- [ ] Did you mark as `Please Merge`?

### CODE REVIEW

File: src/main/scala/chisel3/util/BitPat.scala [hunk 1]
```diff
@@ -90,7 +90,7 @@ object BitPat {
     */
   def apply(x: UInt): BitPat = {
     val len = if (x.isWidthKnown) x.getWidth else 0
-    apply("b" + x.litValue.toString(2).reverse.padTo(len, "0").reverse.mkString)
+    apply("b" + x.litOption.getOrElse(throw new ChiselException(s"$x is not a literal, BitPat.apply(x: UInt) only accept literal")).toString(2).reverse.padTo(len, "0").reverse.mkString)
```
Comment (jackkoenig) [inline src/main/scala/chisel3/util/BitPat.scala:93]:
```suggestion
    x.litOption match {
      case Some(lit) => apply("b" + lit.toString(2).reverse.padTo(len, "0").reverse.mkString)
      case None => throwException(s"$x is not a literal, BitPat.apply(x: UInt) only accepts literals")
    }
```
Good to have a more clear error message, the line is just a bit long with it in a single line 🙂

**Review by jackkoenig — APPROVED** [review]
